@startuml Admin

actor Admin


Admin -> API_Gateway: Send request 

API_Gateway -> API_Gateway : Validate Authenticate

    alt Authentication failed

    API_Gateway -> Admin : Response forbiden 

    else Authentication successful

    API_Gateway -> API_Gateway : Read data(billing, transaction linked product, customer, agency) that can be accessed

    API_Gateway -> Admin : Response data
    end

@enduml